# 服务配置
server:
  port: 8085
  servlet:
    application-display-name: actdemo

# Spring相关配置
spring:
  security:
    user:
      password: 123
      name: user
  ##数据库连接信息
  datasource:
    # 数据源配置
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 991226Ab#
    driver-class-name: com.mysql.cj.jdbc.Driver

    # SQLException: XAER_INVAL: Invalid arguments (or unsupported command)问题
    xa:
      properties:
        pinGlobalTxToPhysicalConnection: true
        useServerPrepStmts: true
  application:
    # 注册应用名
    name: actdemo
  # 参考配置https://www.cnblogs.com/liaojie970/p/8857710.html
  activiti:
    # 自动建表
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true